# Generated by Django 3.2.9 on 2021-11-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('indicativo', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('docIdentidad', models.IntegerField()),
            ],
        ),
    ]
