# Generated by Django 3.2.9 on 2021-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0003_alter_formulario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
